### ISSUE TITLE
KeyError on Editing Bot Description

### ISSUE THREAD

**Issue by ManinderAngural** [devakira/konomi-bots#6]
### Submitting bot after editing long description ends in KeyError: 'owner'

* Methods to reproduce
1. Edit your bot's long description
2. Submit bot

* Expected Result
Updated description without errors

* Actual Result 
Lands on error page with KeyError: 'owner' and its traceback

https://cdn.discordapp.com/attachments/354992261601165313/470693283828334602/unknown.png

**Comment by ManinderAngural** [comment]
![Screenshot](https://user-images.githubusercontent.com/32453698/43050308-50e38324-8e24-11e8-8bfb-05f0b1b09eed.png)

**Comment by devakira** [comment]
Should be fixed.
