### ISSUE TITLE
Keyerror while trying to view a bot page when logged out

### ISSUE THREAD

**Issue by Nexus237** [devakira/konomi-bots#7]
**Methods to reproduce**
- Log out / Do not login
- Click on 'View' any bot

**Expected Result**
- Lands on the Viewing (Main) page of the bot

**Actual Result**
- Lands on an error page

https://discord.is-down.party/B9nHvHc9.png

**Comment by devakira** [comment]
Please screenshot the full traceback

**Comment by Shea4** [comment]
![image](https://user-images.githubusercontent.com/38985791/43081744-3df7b90e-8e8a-11e8-960b-1df2f73dffeb.png)

**Comment by Nexus237** [comment]
@devakira ^
@Shea4 Thanks <3

**Comment by devakira** [comment]
Fixed in latest patch
